table lojas
	lineageTag: 92d6d533-7b6a-4b75-bad3-97721d6ec365

	column codigo_loja
		dataType: string
		lineageTag: ba108673-ab4a-44b9-bac6-3b191824e2cd
		summarizeBy: none
		sourceColumn: codigo_loja

		annotation SummarizationSetBy = Automatic

	column nome_loja
		dataType: string
		lineageTag: db369e1e-1b7d-4a63-8498-11b821c0fac8
		summarizeBy: none
		sourceColumn: nome_loja

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 4d52e8eb-c235-4585-b09a-bdb6d63a4f6d
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 8b2ef646-fb04-4b6a-9e71-f404c9b04c88
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	partition lojas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\rafae\Downloads\bd_vendas.xlsx"), null, true),
				    lojas_Sheet = Fonte{[Item="lojas",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(lojas_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"codigo_loja", type text}, {"nome_loja", type text}, {"Cidade", type text}, {"UF", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

