table Vendas
	lineageTag: c21301f8-55d0-4297-90a8-b881882fa50d

	measure Comissao = SUM(Vendas[Valor Venda])* 0.05
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 8bb50886-f002-473a-8a50-5e631afc5c83

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'ID Pedido'
		dataType: string
		lineageTag: eff92cbe-741b-44a0-983a-0843a55eb602
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Data Pedido'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cbc39706-86ab-499b-9b2b-218ad221d784
		summarizeBy: none
		sourceColumn: Data Pedido

		variation Variation
			isDefault
			relationship: 780cf0de-93fb-45b7-963a-1e92f70ce743
			defaultHierarchy: LocalDateTable_83178412-3e3a-4bde-a063-714b80f833f2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Código Loja'
		dataType: string
		lineageTag: f170e3d7-4ca4-45f1-8f09-5231bceb13dd
		summarizeBy: none
		sourceColumn: Código Loja

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: 7c125845-b8ba-4aae-8be3-7b00b9907fbe
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: 92f8958c-19e5-48ea-8f85-034b543d550e
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column 'Preco Unitario'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 8fd60418-c3f0-40a4-ac17-40a52ed97163
		summarizeBy: sum
		sourceColumn: Preco Unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Pagamento
		dataType: string
		lineageTag: c01668b8-1760-4387-9ca9-2d72ad515495
		summarizeBy: none
		sourceColumn: Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Valor Venda'
		dataType: decimal
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 9dbdc715-a427-4af1-8a22-f9f8f397d171
		summarizeBy: sum
		sourceColumn: Valor Venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\rafae\Downloads\bd_vendas.xlsx"), null, true),
				    registroVendas_Sheet = Fonte{[Item="registroVendas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(registroVendas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Pedido", type text}, {"Data Pedido", type date}, {"Código Loja", type text}, {"Produto", type text}, {"Qtde/Preco Unit", type text}, {"Pagamento", type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","Malaa","Mala",Replacer.ReplaceText,{"Produto"}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Valor Substituído",{{"Produto", Text.Proper, type text}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Colocar Cada Palavra Em Maiúscula", "Qtde/Preco Unit", Splitter.SplitTextByDelimiter("/", QuoteStyle.Csv), {"Qtde/Preco Unit.1", "Qtde/Preco Unit.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Qtde/Preco Unit.1", Int64.Type}, {"Qtde/Preco Unit.2", type number}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Qtde/Preco Unit.1", "Quantidade"}, {"Qtde/Preco Unit.2", "Preco Unitario"}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Preco Unitario", Currency.Type}}),
				    #"Multiplicação Inserida" = Table.AddColumn(#"Tipo Alterado2", "Multiplicação", each [Quantidade] * [Preco Unitario], Currency.Type),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Multiplicação Inserida",{{"Multiplicação", "Valor Venda"}})
				in
				    #"Colunas Renomeadas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

